name: digital_life_care_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  provider: ^6.1.2 # State management (MVVM)
  go_router: ^17.0.0 # Navigation
  google_fonts: ^6.2.1 # Fonts
  shared_preferences: ^2.3.2 # Local storage
  hive: ^2.2.3 # Offline caching
  hive_flutter: ^1.1.0 # Hive init
  image_picker: ^1.1.2 # Profile photo
  flutter_colorpicker: ^1.1.0 # Theme color
  geolocator: ^14.0.2 # GPS (later)
  dio: ^5.7.0 # HTTP (API stubs)
  flutter_local_notifications: ^19.5.0 # Reminders
  uuid: ^4.5.1
  google_maps_flutter: ^2.7.0 # Locator
  qr_flutter: ^4.1.0 # QR codes
  fl_chart: ^1.1.1 # Analytics
  share_plus: ^12.0.0 # Sharing
  flutter_image_compress: ^2.3.0 # Photo compress
  carousel_slider: ^5.1.1 # Onboarding
  table_calendar: ^3.1.2 # Booking
  timelines: ^0.1.0 # Reminders timeline
  crypto: ^3.0.5 # Encryption stubs
  url_launcher: ^6.2.2
  file_picker: ^10.3.7
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.jpg