import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';

import 'package:digital_life_care_app/providers/auth_provider.dart';
import 'package:digital_life_care_app/providers/user_provider.dart';
import 'package:digital_life_care_app/providers/reminder_provider.dart';
import 'package:digital_life_care_app/providers/awareness_provider.dart';
import 'package:digital_life_care_app/providers/chat_provider.dart';

import 'package:digital_life_care_app/screens/auth/login_screen.dart';
import 'package:digital_life_care_app/screens/auth/register_screen.dart';
import 'package:digital_life_care_app/screens/onboarding_screen.dart';
import 'package:digital_life_care_app/screens/awareness/awareness_home_screen.dart';
import 'package:digital_life_care_app/screens/awareness/awareness_detail_screen.dart';
import 'package:digital_life_care_app/screens/health_worker/health_worker_shell.dart';
import 'package:digital_life_care_app/screens/health_worker/hw_chat_detail_screen.dart';
import 'package:digital_life_care_app/screens/health_worker/hw_awareness_upload_screen.dart';
import 'package:digital_life_care_app/screens/health_worker/hw_awareness_detail_screen.dart';
import 'package:digital_life_care_app/screens/reminder.dart';
import 'package:digital_life_care_app/screens/home_shell.dart'; // student shell / dashboard
import 'package:digital_life_care_app/screens/profile_screen.dart';
import 'package:digital_life_care_app/screens/splash_screen.dart';
import 'package:digital_life_care_app/screens/booking.dart';
import 'package:digital_life_care_app/screens/chat/chat_home_screen.dart';
import 'package:digital_life_care_app/screens/locator/locator_list_screen.dart';
import 'package:digital_life_care_app/screens/delivery_screen.dart';
import 'package:digital_life_care_app/screens/analytics_screen.dart';

import 'package:digital_life_care_app/providers/locator_provider.dart'; // Add this import
import 'package:digital_life_care_app/widgets/route_guard.dart';

import 'firebase_options.dart'; // generated by CLI

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const RootApp());
}

class RootApp extends StatelessWidget {
  const RootApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthProvider()..initialize()),
        ChangeNotifierProvider(create: (_) => UserProvider()..initialize()),
        ChangeNotifierProvider(create: (_) => AwarenessProvider()),
        ChangeNotifierProvider(create: (_) => ReminderProvider()..initialize()),
        ChangeNotifierProvider(create: (_) => ChatProvider()),
        ChangeNotifierProvider(
          create: (_) => LocatorProvider(),
        ), // Add this line
      ],
      child: Consumer<UserProvider>(
        builder: (context, user, _) => MaterialApp(
          title: 'Digital Life Care',
          debugShowCheckedModeBanner: false,
          theme: ThemeData(
            useMaterial3: true,
            colorScheme:
                ColorScheme.fromSeed(
                  seedColor: Colors.blue,
                  brightness: user.isDark ? Brightness.dark : Brightness.light,
                ).copyWith(
                  surface: user.isDark
                      ? const Color(0xFF263238)
                      : const Color(0xFFF2F2F2),
                  primary: const Color(0xFF1976D2),
                  onPrimary: Colors.white,
                ),
            scaffoldBackgroundColor: user.isDark
                ? const Color(0xFF0D47A1)
                : const Color(0xFFB3E5FC),
            cardTheme: const CardThemeData(
              color: Color(0xFFF2F2F2),
              margin: EdgeInsets.all(12),
            ),
            elevatedButtonTheme: ElevatedButtonThemeData(
              style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFF1976D2),
                foregroundColor: Colors.white,
                minimumSize: const Size.fromHeight(48),
                shape: const RoundedRectangleBorder(
                  borderRadius: BorderRadius.all(Radius.circular(8)),
                ),
              ),
            ),
            textButtonTheme: TextButtonThemeData(
              style: TextButton.styleFrom(
                foregroundColor: const Color(0xFF1976D2),
              ),
            ),
            navigationBarTheme: NavigationBarThemeData(
              backgroundColor: Colors.transparent,
              indicatorColor: const Color(0xFF2E7D32),
              surfaceTintColor: Colors.transparent,
              labelBehavior: NavigationDestinationLabelBehavior.alwaysShow,
              labelTextStyle: WidgetStateProperty.all(
                const TextStyle(color: Colors.white),
              ),
              iconTheme: WidgetStateProperty.all(
                const IconThemeData(color: Colors.white),
              ),
            ),
            appBarTheme: const AppBarTheme(
              backgroundColor: Colors.transparent,
              elevation: 0,
              scrolledUnderElevation: 0,
            ),
          ),
          initialRoute: '/splash',
          routes: {
            '/splash': (_) => const SplashScreen(),
            '/onboarding': (_) => const OnboardingScreen(),
            '/login': (_) => const LoginScreen(),
            '/register': (_) => const RegisterScreen(),
            // Student routes - protected from health workers
            '/profile': (_) => Builder(
              builder: (context) {
                // Double check at route level - if health worker, redirect immediately
                final userProvider = Provider.of<UserProvider>(context, listen: false);
                Provider.of<AuthProvider>(context, listen: false);
                final role = userProvider.role;
                final isHW = role == 'health_worker' || role == 'worker';
                if (isHW) {
                  // Redirect immediately without building the screen
                  WidgetsBinding.instance.addPostFrameCallback((_) {
                    if (context.mounted) {
                      Navigator.of(context).pushNamedAndRemoveUntil('/hw', (route) => false);
                    }
                  });
                  return const Scaffold(body: SizedBox.shrink());
                }
                return StudentRouteGuard(
                  routeName: '/profile',
                  child: const ProfileScreen(),
                );
              },
            ),
            '/dashboard': (_) => StudentRouteGuard(
                  routeName: '/dashboard',
                  child: const HomeShell(),
                ),
            '/awareness': (_) => StudentRouteGuard(
                  routeName: '/awareness',
                  child: const AwarenessHomeScreen(),
                ),
            '/booking': (_) => StudentRouteGuard(
                  routeName: '/booking',
                  child: const BookingScreen(),
                ),
            '/reminder': (_) => StudentRouteGuard(
                  routeName: '/reminder',
                  child: const ReminderScreen(),
                ),
            '/chat': (_) => StudentRouteGuard(
                  routeName: '/chat',
                  child: const ChatHomeScreen(),
                ),
            '/locator': (_) => StudentRouteGuard(
                  routeName: '/locator',
                  child: const LocatorListScreen(),
                ),
            '/delivery': (_) => StudentRouteGuard(
                  routeName: '/delivery',
                  child: const DeliveryScreen(),
                ),
            '/analytics': (_) => StudentRouteGuard(
                  routeName: '/analytics',
                  child: const AnalyticsScreen(),
                ),
            // Health worker routes
            '/hw': (_) => const HealthWorkerShell(),
            '/hw/awareness/upload': (_) => const HWAwarenessUploadScreen(),
          },
          onGenerateRoute: (settings) {
            if (settings.name == '/awareness/detail') {
              return MaterialPageRoute(
                builder: (_) => StudentRouteGuard(
                  routeName: '/awareness/detail',
                  child: const AwarenessDetailScreen(),
                ),
                settings: settings,
              );
            }
            if (settings.name == '/hw/awareness/detail') {
              final args = settings.arguments as Map<String, dynamic>?;
              if (args == null) {
                return MaterialPageRoute(
                  builder: (_) => const _RouteErrorScreen(
                    message: 'Missing awareness data',
                  ),
                  settings: settings,
                );
              }
              return MaterialPageRoute(
                builder: (_) => HWAwarenessDetailScreen(data: args),
                settings: settings,
              );
            }
            if (settings.name == '/hw/chat/detail') {
              final id = settings.arguments as String?;
              if (id == null || id.isEmpty) {
                return MaterialPageRoute(
                  builder: (_) => const _RouteErrorScreen(
                    message: 'Missing or invalid request id',
                  ),
                  settings: settings,
                );
              }
              return MaterialPageRoute(
                builder: (_) => HWChatDetailScreen(requestId: id),
                settings: settings,
              );
            }
            return null;
          },
        ),
      ),
    );
  }
}

// add near the end of file (below RootApp) — simple routing error screen
class _RouteErrorScreen extends StatelessWidget {
  final String message;
  const _RouteErrorScreen({required this.message});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Navigation Error')),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Text(message, textAlign: TextAlign.center),
        ),
      ),
    );
  }
}
